---
title: "Fish-PACE"
favicon: "favicon.ico"
output:
  postcards::trestles
site: distill::distill_website
---

New satellite missions for the ocean environment—NASA's PACE (Plankton, Aerosol, Cloud, ocean Ecosystem) launched in February 2024 and the upcoming GeoXO (Geostationary Extended Observations)—are poised to revolutionize ocean color observation by providing much higher spectral resolution and more frequent, near-real-time data. These advanced missions will significantly enhance our ability to monitor dynamic coastal ecosystems, improving both the accuracy and timeliness of environmental assessments and decision-making. The Fish-PACE project works to help people use these new products and innovate using them.


## Trainings

* [EDMW 2025](https://nmfs-opensci.github.io/EDMW-EarthData-Workshop-2025/) Introduction to using earth data in the cloud for scientific workflows: PACE hyperspectral ocean color data
* [Fish-PACE HackWeek 2026](https://fish-pace.github.io/hackweek-2025/) Virtual Jan 26-30, 2026
* HyperDawg: Bi-weekly informal discussions and experimentation
* [NMFS HackHours](https://nmfs-opensci.github.io/NMFSHackDays-2025/): Though not hyperspectral focused, much of the training is relevant to working with hyperspectral data.

